### ISSUE TITLE
How can I install this?

### ISSUE THREAD

**Issue by ghost** [DiamondIceNS/Hungrybot#1]
Hi! I wanna try out your hunger games bot for my discord server. But I am having some troubles, I have everything needed installed. I can't figure out how to install it though. I already have a token. If you can help me out with this, that would be great!

**Comment by DiamondIceNS** [comment]
Hi there! Sorry the bot is really confusing, this was a bit of a shitpost project that I intended to revisit later.

I believe the way to get it working is to put your token into `config_example.py` and then rename the file to `config.py`, and run `hungrybot.py`.
